# Generated by Django 4.2.5 on 2023-11-04 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=35, verbose_name='Nombre')),
                ('sigla', models.CharField(max_length=10, verbose_name='Sigla')),
                ('activo', models.BooleanField(default=False, verbose_name='¿Está activo?')),
                ('piso', models.PositiveSmallIntegerField(verbose_name='Piso')),
                ('oficina', models.CharField(max_length=7, verbose_name='Oficina N°')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Departamentos',
                'ordering': ['nombre'],
                'unique_together': {('nombre', 'sigla')},
            },
        ),
    ]
