# Generated by Django 4.2.5 on 2023-11-04 18:58

import aplicaciones.descuentos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Código')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('descuento_porcentaje', models.IntegerField(blank=True, null=True, validators=[aplicaciones.descuentos.models.validate_two_digit], verbose_name='Porcentaje de descuento')),
                ('descuento_valor', models.IntegerField(blank=True, null=True, verbose_name='Valor de descuento')),
                ('compartido', models.BooleanField(default=True, verbose_name='¿Es compartido?')),
            ],
            options={
                'verbose_name': 'Cupón',
                'verbose_name_plural': 'Cupones',
                'ordering': ['fecha'],
            },
        ),
    ]
