# Generated by Django 4.2.5 on 2023-11-04 18:58

import aplicaciones.usuario.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Email address')),
                ('password', models.CharField(max_length=100, verbose_name='Password')),
                ('username', models.CharField(blank=True, max_length=30, verbose_name='Username')),
                ('nombre', models.CharField(blank=True, max_length=20, null=True, verbose_name='Nombre')),
                ('apellido', models.CharField(blank=True, max_length=20, null=True, verbose_name='Apellido')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff')),
                ('is_superuser', models.BooleanField(default=True, verbose_name='Superuser')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Admin')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('groups', models.ManyToManyField(related_name='custom_user_set', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(related_name='custom_user_set', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            managers=[
                ('objects', aplicaciones.usuario.models.UserManager()),
            ],
        ),
    ]
